const cats = [
    { cat_id: 'CAT000', name: '测试用', area: '测试用', specific_location: 'CUG校内' },
    { cat_id: 'CAT999', name: '测试用', area: '测试用', specific_location: 'CUG全境' },
    { cat_id: 'CAT005', name: '海胆', area: '各学院', specific_location: '环院&池塘附近' },
    { cat_id: 'CAT007', name: '花臂', area: '宿舍区', specific_location: '一组团' },
    { cat_id: 'CAT008', name: '圆圆', area: '各学院', specific_location: '环院' },
    { cat_id: 'CAT009', name: '二号楼', area: '各学院', specific_location: '环院' },
    // { cat_id: 'CAT010', name: '冷巴', area: '其它区域', specific_location: '未知' },
    { cat_id: 'CAT011', name: '丑丑', area: '各学院', specific_location: '环院' },
    //{ cat_id: 'CAT012', name: '晨光', area: '公共区域', specific_location: '驿站' },
    //{ cat_id: 'CAT014', name: '小爱心', area: '宿舍区', specific_location: '二组团' },
    //{ cat_id: 'CAT025', name: '海星', area: '宿舍区', specific_location: '二组团' },
    //{ cat_id: 'CAT036', name: '玳瑁妈妈', area: '宿舍区', specific_location: '二组团' },
    //{ cat_id: 'CAT040', name: '松花蛋', area: '宿舍区', specific_location: '二组团' },
    { cat_id: 'CAT046', name: '乌云', area: '宿舍区', specific_location: '一组团' },
    //{ cat_id: 'CAT044', name: '小小酥', area: '其它区域', specific_location: '驿站' },
    { cat_id: 'CAT047', name: '小乌云', area: '宿舍区', specific_location: '二组团' },
    //{ cat_id: 'CAT050', name: '碎冰冰', area: '其它区域', specific_location: '团书馆' },
    //{ cat_id: 'CAT051', name: '臭臭', area: '各学院', specific_location: '计算机' },
    { cat_id: 'CAT052', name: '麦乐鸡', area: '其它区域', specific_location: '图书馆' },
    //{ cat_id: 'CAT053', name: '大白', area: '宿舍区', specific_location: '二组团' },
    { cat_id: 'CAT054', name: '糖爹', area: '宿舍区', specific_location: '一组团' },
    { cat_id: 'CAT060', name: '蛋仔', area: '宿舍区', specific_location: '一组团' },
    //{ cat_id: 'CAT062', name: '假贴贴', area: '宿舍区', specific_location: '二组团&驿站' },
    { cat_id: 'CAT063', name: '喇叭', area: '其它区域', specific_location: '图书馆' },
    { cat_id: 'CAT070', name: '线面', area: '其它区域', specific_location: '图书馆' },
    { cat_id: 'CAT071', name: '花卷', area: '各学院', specific_location: '环院' },
    { cat_id: 'CAT072', name: '旺仔', area: '各学院', specific_location: '环院' },
    //{ cat_id: 'CAT078', name: '白尾', area: '宿舍区', specific_location: '一组团' },
    { cat_id: 'CAT079', name: '小贼', area: '宿舍区', specific_location: '一、二组团' },
    { cat_id: 'CAT080', name: '肯德基', area: '各学院', specific_location: '环院、二组团' },
    { cat_id: 'CAT082', name: '凶凶', area: '宿舍区', specific_location: '四组团' },
    { cat_id: 'CAT083', name: '大盗', area: '宿舍区', specific_location: '三组团' },
    { cat_id: 'CAT084', name: '海口', area: '宿舍区', specific_location: '二、三组团' },
    { cat_id: 'CAT085', name: '黄鼠狼', area: '其它区域', specific_location: '图书馆' },
    { cat_id: 'CAT087', name: '麻雀', area: '宿舍区', specific_location: '二组团' },
    { cat_id: 'CAT088', name: '宽宽', area: '各学院', specific_location: '环院' },
    { cat_id: 'CAT089', name: '窄窄', area: '各学', specific_location: '环院&四组团' },
    { cat_id: 'CAT090', name: '三亚', area: '宿舍区', specific_location: '二组团' },
    { cat_id: 'CAT091', name: '凶凶跟班小橘', area: '宿舍区', specific_location: '四组团' },
    { cat_id: 'CAT092', name: '丑橘', area: '宿舍区', specific_location: '四组团' },
    { cat_id: 'CAT093', name: '半白半菊', area: '宿舍区', specific_location: '四组团' },
    { cat_id: 'CAT094', name: '雪里拖枪', area: '宿舍区', specific_location: '未知' },
    
    // ... 其他猫咪数据 ...
  ];
  module.exports = cats;